class Autogenerated {
  String? code;
  Data? data;
  String? message;

  Autogenerated({this.code, this.data, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    data['message'] = this.message;
    return data;
  }
}

class Data {
  String token;
  UserDetail userDetail;

  Data({this.token, this.userDetail});

  Data.fromJson(Map<String, dynamic> json) {
    token = json['token'];
    userDetail = json['userDetail'] != null
        ? new UserDetail.fromJson(json['userDetail'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['token'] = this.token;
    if (this.userDetail != null) {
      data['userDetail'] = this.userDetail.toJson();
    }
    return data;
  }
}

class UserDetail {
  String username;
  bool accountNonExpired;
  bool accountNonLocked;
  bool credentialsNonExpired;
  bool enabled;
  String userType;
  String userUid;
  String realName;
  int titleId;
  int countryCode;
  String phone;

  UserDetail(
      {this.username,
      this.accountNonExpired,
      this.accountNonLocked,
      this.credentialsNonExpired,
      this.enabled,
      this.userType,
      this.userUid,
      this.realName,
      this.titleId,
      this.countryCode,
      this.phone});

  UserDetail.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    accountNonExpired = json['accountNonExpired'];
    accountNonLocked = json['accountNonLocked'];
    credentialsNonExpired = json['credentialsNonExpired'];
    enabled = json['enabled'];
    userType = json['userType'];
    userUid = json['userUid'];
    realName = json['realName'];
    titleId = json['titleId'];
    countryCode = json['countryCode'];
    phone = json['phone'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['username'] = this.username;
    data['accountNonExpired'] = this.accountNonExpired;
    data['accountNonLocked'] = this.accountNonLocked;
    data['credentialsNonExpired'] = this.credentialsNonExpired;
    data['enabled'] = this.enabled;
    data['userType'] = this.userType;
    data['userUid'] = this.userUid;
    data['realName'] = this.realName;
    data['titleId'] = this.titleId;
    data['countryCode'] = this.countryCode;
    data['phone'] = this.phone;
    return data;
  }
}
