name: Flutter Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build web
        run: flutter build web --release --base-href /json2dart/
      
      - name: Create Release Archive
        run: |
          cd build/web
          zip -r ../../json2dart-web.zip .
          cd ../..
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: json2dart-web.zip
          name: Release ${{ github.ref_name }}
          body: |
            JSON to Dart Converter Web Release
            
            This release contains the compiled web application.
            
            ## Installation
            1. Download the zip file
            2. Extract it to your web server
            3. Access through your web server
            
            ## Direct Usage
            You can also use the online version at: https://invincible1996.github.io/json2dart/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
